name: Merge request for Phishing
description: File a Phishing report
assignees:
  - mitchellkrogza
body:
- type: textarea
  attributes:
    label: Domain/URL/IP(s) where you have found the Phishing
    description: |
      List the Domain/URL/IP for where the phishing occurs is
      **mandatory**. 
      The backticks (`) surrounding the Domain/URL/IPs are important,
      it prevents the URL from becoming clickable.
      
      Warn with "NSFW" where applicable.

      **Help** To make the right commit for IP-addresses you have to
      also prefix the CIDR notation, if you don't know what a CIDR
      notation is, the right value is most likely `/32`, which in short
      means exactly this IP address.
    placeholder: |
      `https://example.com`
      `https://example.org/phishing`
      `192.0.2.0/24`
    render: true
  validations:
    required: true

- type: textarea
  attributes:
    label: Related external source
    description: |
      If you have found your information in another fora, please paste
      link here.

      One link per line.
    placeholder: |
      https://mypdns.org
  validations:
    required: false

- type: textarea
  attributes:
    label: Describe the issue
    description: |
      Be as clear as possible: nobody can read your mind, and nobody
      is looking at your issue over your shoulder.
  validations:
    required: true

- type: textarea
  attributes:
    label: Screenshot
    id: Screenshot
    description: |
      If you feel a screenshot can say more than 1000 hard drives, do
      please feel free to add it here :smiley:

      **TIP** Place your mouse on the line just above the `</details>`
      and paste your screenshot and make sure that there is at least one
      line spacing before and after the image code line. The tip will add"
      one line after the paste :wink:
      
      ```html
      <details><summary>Click to expand</summary>
      
      
      </details>
      ```
  validations:
    required: false
