name: Phishing Report
description: File a Phishing report
assignees:
  - mitchellkrogza
  - funilrys
body:
  - type: textarea
    attributes:
      label: Domain/URL/IP(s) where you have found the Phishing
      description: |
        List the Domain/URL/IP for where the phishing occurs is
        **mandatory**. 
        The backticks (`) surrounding the Domain/URL/IPs are important,
        it prevents the URL from becoming clickable.

        Warn with "NSFW" where applicable.

        **Help** To make the right commit for IP-addresses you have to
        also prefix the CIDR notation, if you don't know what a CIDR
        notation is, the right value is most likely `/32`, which in short
        means exactly this IP address.
      placeholder: |
        example.com
        https://example.org/phishing
        192.0.2.0/24
      render: Markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: Impersonated domain
      description: |
        Provide the FQDN domain for which you believes is the victim site.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the issue
      description: |
        Be as clear as possible: nobody can read your mind, and nobody
        is looking at your issue over your shoulder.
    validations:
      required: true

  - type: textarea
    id: Screenshot
    attributes:
      label: Screenshot
      description: |
        If you feel a screenshot can say more than 1000 hard drives, do
        please feel free to add it here :smiley:

        **INFO** There need to be at least one blank line separating before
        and after the image line

        Copy and paste the lines to the text area below.

        ```
        <details><summary>Click to expand</summary>


        </details>
        ```
      render: Markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Related external source
      description: |
        If you have found your information in another fora, please paste
        link here.

        One link per line.
      placeholder: |
        https://example.org
    validations:
      required: false
